#include "graphics.h"
#include "gba.h"
#include "logic.h"
#include "stdio.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
#include "images/titan_1.h"
#include "images/characters.h"
#include "images/gauntlet.h"
#include "images/win.h"
#include "images/ironman.h"
#include "images/captain.h"
#include "images/thor.h"
#include "images/arrow.h"

// Draw Hero's and Enemy's HP
static void drawHP(Avenger hero, Enemy enemy) {
    drawRectDMA(68, 0, 100, 15, GRAY);
    char avengerHP[51]; // draw the score
    sprintf(avengerHP, "HP:%d", hero.hp);
    drawCenteredString(85, 5, 20, 10, avengerHP, RED);
    
    char enemyHP[51]; // draw the score
    sprintf(enemyHP, "HP:%d", enemy.hp);
    drawCenteredString(130, 5, 20, 10, enemyHP, RED);
}

// Draw Hero and Enemy character
static void drawHeroAndEnemy(AppState *state, Avenger hero, Enemy enemy) {
    if (state->character_index == 0) {
        drawIronmanVSThanos(hero.x, hero.y, enemy.x, enemy.y);
    } else if (state->character_index == 1) {
        drawCaptainVSThanos(hero.x, hero.y, enemy.x, enemy.y);
    } else if (state->character_index == 2) {
        drawThorVSThanos(hero.x, hero.y, enemy.x, enemy.y);
    }
}

// This function will be used to draw everything about the state of your character choice app
void drawFullChacterChoices(AppState *state) {
    fillScreenDMA(BLACK);
    drawCenteredString(65, 10, 100, 40, "Choose a hero and press A", WHITE);
    
    drawImageDMA(25, 63, 50, 60, ironman);
    drawImageDMA(95, 65, 50, 60, captain);
    drawImageDMA(165, 60, 50, 60, thor);

    drawCenteredString(0, 110, 100, 40, "Ironman", WHITE);
    drawCenteredString(70, 110, 100, 40, "Captain", GRAY);
    drawCenteredString(70, 120, 100, 40, "America", GRAY);
    drawCenteredString(138, 110, 100, 40, "Thor", GRAY);
    
    drawImageDMA(state->character_arrow.x, state->character_arrow.y, 10, 20, arrow);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame in character choice screen
void undrawChracterAppState(AppState *state) {
    drawRectDMA(state->character_arrow.x, state->character_arrow.y, 30, 30, BLACK);
    drawRectDMA(0, 110, 100, 40, BLACK);
    drawRectDMA(70, 110, 100, 40, BLACK);
    drawRectDMA(70, 120, 100, 40, BLACK);
    drawRectDMA(138, 110, 100, 40, BLACK);
}

// This function will be used to draw (i.e. erase) things that might
// move in a frame in character choice screen
void drawCharacterAppState(AppState *state) {
    if (state->character_index == 0) {
        drawCenteredString(0, 110, 100, 40, "Ironman", WHITE);
        drawCenteredString(70, 110, 100, 40, "Captain", GRAY);
        drawCenteredString(70, 120, 100, 40, "America", GRAY);
        drawCenteredString(138, 110, 100, 40, "Thor", GRAY);
    } else if (state->character_index == 1) {
        drawCenteredString(0, 110, 100, 40, "Ironman", GRAY);
        drawCenteredString(70, 110, 100, 40, "Captain", WHITE);
        drawCenteredString(70, 120, 100, 40, "America", WHITE);
        drawCenteredString(138, 110, 100, 40, "Thor", GRAY);
    } else if (state->character_index == 2) {
        drawCenteredString(0, 110, 100, 40, "Ironman", GRAY);
        drawCenteredString(70, 110, 100, 40, "Captain", GRAY);
        drawCenteredString(70, 120, 100, 40, "America", GRAY);
        drawCenteredString(138, 110, 100, 40, "Thor", WHITE);
    }
    drawImageDMA(state->character_arrow.x, state->character_arrow.y, 10, 20, arrow);
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(BLACK);
    drawImageDMA(0, 16, 240, 145, titan_1);
    drawHeroAndEnemy(state, state->hero, state->enemy);
    drawHP(state->hero, state->enemy);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    //fillScreenDMA(BLACK);
    drawImageDMA(0, 16, 240, 145, titan_1);
    drawRectDMA(68, 0, 100, 15, BLACK);
    drawHP(state->hero, state->enemy);
    if (state->al.shot == 1) {
        drawRectDMA(state->al.x-1, state->al.y, 5, 5, BLUE);
    }
    if (state->el.shot == 1) {
        drawRectDMA(state->el.x - 1, state->el.y, 5, 5, RED);
    }
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    drawHeroAndEnemy(state, state->hero, state->enemy);
    drawHP(state->hero, state->enemy);
}

// This function will be used to draw the ending
void drawEnding(AppState *state) {
    eraseCharacters();
    if (state->won == 0) {
        drawFullScreenImageDMA(gauntlet);
        drawCenteredString(60, 60, 100, 80, "SNAP", WHITE);
        drawCenteredString(60, 80, 100, 80, "THE END", WHITE);
        drawCenteredString(65, 100, 100, 80, "PRESS START TO PLAY AGAIN", WHITE);
    } else {
        drawFullScreenImageDMA(win);
        drawCenteredString(65, 85, 100, 80, "YOU SAVED THE WORLD", WHITE);
        drawCenteredString(65, 100, 100, 80, "PRESS START TO PLAY AGAIN", WHITE);
    }
}
